name = "dfkwebsite"
main = "src/index.ts"
compatibility_date = "2023-03-13"

kv_namespaces = [
  { binding = "NEWS", id = "86cdd1ce931747f897b9328306e0b30a", preview_id="86cdd1ce931747f897b9328306e0b30a" }
]

[env.prod]
name = "dfkwebsite-prod"
kv_namespaces = [
  { binding = "NEWS", id = "86cdd1ce931747f897b9328306e0b30a"},
]